sudo: required
services:
  - docker

before_install:
  - docker build -t hayasam/docker-react-nginx -f Dockerfile.dev .

script:
  - docker run hayasam/docker-react-nginx npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerWithReact"
  env: "Dockerwithreact-env"
  # created automatically from beanstalk on S3 (part of Hard drive to store zipped files of app)
  bucket_name: "elasticbeanstalk-us-east-2-172890911092"
#   Same name as app
  bucket_path: "dockerWithReact"  
  # deploy just when any change on master
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

